{
 "title": "zlmediakit",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "流(stream)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "流数量(count)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    { "expr": "zlm_stream_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "流-观看人数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "sum(zlm_reader_count{})", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "流-码率(bitrate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "zlm_stream_bitrate{}", "legendFormat": "__auto" }
   ]
  },
  { "title": "工作线程(work thread)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "工作线程统计",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    { "expr": "zlm_work_threads_total{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "工作线程延迟统计",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    { "expr": "zlm_work_threads_delay_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "工作线程负载统计",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    { "expr": "zlm_work_threads_load_total", "legendFormat": "__auto" }
   ]
  },
  { "title": "网络线程(network thread)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "网络线程统计",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "targets": [
    { "expr": "zlm_network_threads_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "网络线程延迟情况",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "zlm_network_threads_delay_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "网络线程负载情况",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    { "expr": "zlm_network_threads_load_total", "legendFormat": "__auto" }
   ]
  },
  { "title": "api统计情况", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "api启用情况",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
   "targets": [
    { "expr": "zlm_api_status", "legendFormat": "{{label_name}}" }
   ]
  },
  { "title": "主要对象个数统计", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "主要对象个数统计-Tcp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "targets": [
    { "expr": "zlm_statistics_udp_server", "legendFormat": "udpServer" },
    {
     "expr": "zlmediakit_statistics_udp_session",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "主要对象个数统计-Socket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "targets": [
    { "expr": "zlm_statistics_socket", "legendFormat": "socket" }
   ]
  },
  {
   "title": "主要对象个数统计-Tcp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "targets": [
    { "expr": "zlm_statistics_tcp_client", "legendFormat": "__auto" },
    {
     "expr": "zlmediakit_statistics_tcp_server",
     "legendFormat": "__auto"
    },
    {
     "expr": "zlmediakit_statistics_tcp_session",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "主要对象个数统计-Buffer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "targets": [
    { "expr": "zlm_statistics_buffer", "legendFormat": "buffer" },
    {
     "expr": "zlmediakit_statistics_buffer_like_string",
     "legendFormat": "bufferLikeString"
    },
    {
     "expr": "zlmediakit_statistics_buffer_list",
     "legendFormat": "bufferList"
    },
    {
     "expr": "zlmediakit_statistics_buffer_raw",
     "legendFormat": "bufferRaw"
    }
   ]
  },
  {
   "title": "主要对象个数统计-Frame",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 77 },
   "targets": [
    { "expr": "zlm_statistics_frame", "legendFormat": "frame" },
    {
     "expr": "zlmediakit_statistics_frame_imp",
     "legendFormat": "frameImp"
    }
   ]
  }
 ]
}